spring:
  server:
    port: 8081

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
    org:
      zalando:
        logbook: INFO

logbook:
  write:
    level: INFO

cache-service:
  preference:
    slotNumbers: 10
    timeToLive: 3600
    evictionCachePolicy: OLDER_FIRST


cache:
  version: @project.version@
  suggested-key-properties-ids-for-cache-object: id, ID, Id, iD, name
